In [30]:


import pandas as pd
import numpy as np
from scipy import stats


import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [31]:
url = 'https://github.com/SR1608/KNN/blob/main/Gmat.csv'

In [32]:

td = pd.read_csv("dataa.csv")

In [33]:
td.head()

GMAT Score  Work Exp Admission
0         750         0       Yes
1         720         1       Yes
2         710         2        No
3         690         3        No
4         670         4       Yes

In [34]:

query_data = pd.read_csv("query_point.csv")

In [35]:
query_data = np.array(query_data)
query_data

array([[700,   1]])

In [36]:
def assi_knn(training_data,query_data,k):
    

    query_data = np.array(query_data)
    feature_data = np.array(td.iloc[: , :-1])
    target_data = np.array(td.iloc[: , -1:])

    distances = np.sqrt(np.sum(np.square(query_data - feature_data),axis=1)) 
    sort_index = np.argsort(distances) 
    top_k = sort_index[0:k]   
    nn_classes = target_data[top_k]
    pred = stats.mode(nn_classes)[0][0][0] 
    
    return pred

In [37]:
assi_knn(td,query_data,5)

'Yes'

In [38]:
# If K = 5 amit will not get admission.

In [39]:
fd = np.array(td.iloc[: , :-1])

In [40]:
fd

array([[750,   0],
       [720,   1],
       [710,   2],
       [690,   3],
       [670,   4],
       [650,   5],
       [600,   6]])

In [41]:
target = np.array(td.iloc[: , -1:])

In [42]:
target

array([['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No']], dtype=object)

In [43]:
dis = np.sqrt(np.sum(np.square(query_data - fd),axis=1))

In [44]:
dis

array([ 50.009999  ,  20.        ,  10.04987562,  10.19803903,
        30.14962686,  50.15974482, 100.12492197])

In [45]:
sort_index = np.argsort(dis)
sort_index

array([2, 3, 1, 4, 0, 5, 6])

In [46]:
top_k = sort_index[0:3]
top_k

array([2, 3, 1])

In [47]:
td

GMAT Score  Work Exp Admission
0         750         0       Yes
1         720         1       Yes
2         710         2        No
3         690         3        No
4         670         4       Yes
5         650         5       Yes
6         600         6        No

In [48]:
# Ganesh Anand and Mukesh are top 3 neighbours.